#!/bin/bash

# This script retrieves data for multiple Pokemon automatically and stores it in separate files 


POKEMON_LIST=("bulbasaur" "ivysaur" "venusaur" "charmander" "charmeleon")

API_URL="https://pokeapi.co/api/v2/pokemon/"

# Delay in seconds to avoid rate-limiting
DELAY=2

for POKEMON in "${POKEMON_LIST[@]}"; do # [@] to include each element in the list
    FILE_NAME="${LOWERCASE_NAME}.json"

    echo "Fetching data for $POKEMON..."

    # Fetch data from the API using curl and save it to the corresponding file
    RESPONSE=$(curl -s "${API_URL}${LOWERCASE_NAME}")

    # Check if the request was successful
    # check if last command was successful (0) and response not empty
    if [[ $? -eq 0 && -n "$RESPONSE" ]]; then 
        echo "$RESPONSE" > "$FILE_NAME"
        echo "Data for $POKEMON saved to $FILE_NAME."
    else
        echo "Failed to retrive data for $POKEMON. Check your network or API status."
    fi

    # wait to avoid hitting rate limits
    echo "Waiting for $DELAY seconds..."
    sleep "$DELAY"
done

echo "Data retrieval complete"